In [1]:
print("hello")

hello


In [2]:
num=int(input("enter your number"))
num1=int(input("enetr your second number"))
sum=0
sum=num1+num
print(sum)

enter your number10
enetr your second number12
22


In [7]:
def fun(cowdogcow,cow,dog):
    if cow in cowdogcow :
        return true
    else:
        return false

In [11]:
import numpy as np
a=np.array([2,3,4,5,6,7])
print(a)

[2 3 4 5 6 7]


In [21]:
import numpy as np
b=np.array([[2,3,4],
          [5,6,7],
          [8,9,1]])
b

array([[2, 3, 4],
       [5, 6, 7],
       [8, 9, 1]])

In [18]:
import numpy as np
b = np.arange(start = 20,stop = 30)
b

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [20]:
import numpy as empty
b=np.empty([3,3])
b

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 5.84973725e-321],
       [0.00000000e+000, 0.00000000e+000, 9.51802008e-315]])

In [25]:
from numpy import zeros
b=zeros([4,8])
b

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [26]:
from numpy import ones
b=ones([6])
b

array([1., 1., 1., 1., 1., 1.])

In [30]:
import numpy as np
a1=np.arange(start=1,stop=5)
a2=np.arange(start=2,stop=7)
print(a1.a2) 

AttributeError: 'numpy.ndarray' object has no attribute 'a2'

In [34]:
from numpy import array
from numpy import vstack
a1=np.arange(start=1,stop=5)
print(a1)
a2=np.arange(start=2,stop=7)
print(a2)
a3=vstack(a1,a2)
print(a3)
print(a3.shape)


[1 2 3 4]
[2 3 4 5 6]


TypeError: vstack() takes 1 positional argument but 2 were given

# vstack
from numpy import array
from numpy import vstack
a1 = array([1,2,3])
print(a1)
a2 = array([4,5,6])
print(a2)
a3 = vstack((a1, a2))
print(a3)
print(a3.shape)

In [36]:
##Step1